Makefile
collection_document_impl.go
collection_documents.go
connection.go
context.go
edge_collection_documents_impl.go
http/request.go
http/request_test.go
test/documents_import_test.go
test/edges_import_test.go
test/types.go
test/vertices_import_test.go
vertex_collection_documents_impl.go

Added Collection.ImportDocuments

ImportDocuments

---

Makefile
README.md
cluster/cluster.go
connection.go
context.go
error.go
http/connection.go
http/request.go
http/response.go
http/response_element.go
test/client_test.go
test/failover_test.go

This PR adds tests (and fixes some bugs) regarding automatic failover.
Run the tests using:
```
make run-tests-cluster-failover
```
The test uses `iptables` to actively DROP or REJECT traffic to a random coordinator.
The test succeeds when a certain number of successful failovers has been detected.

Adding failover tests

---

authentication.go
cluster/cluster.go
connection.go
context.go
cursor_impl.go
database_impl.go
error.go
http/connection.go
test/failover_test.go

When a specific endpoint is set, failover is disabled.
`WithEndpoint` is used by Cursor implementation because cursors are only valid in the context of a specific coordinator.
fixed #16

Added WithEndpoint, used to force a specific endpoint for a request. 

---

http/connection.go
test/client_test.go

Using a custom RoundTripper (usually `*http.Transport`) you can customize various connection settings such as proxy behavior, idle connection limits etc.

Allow custom http.RoundTripper

---

cursor.go
cursor_impl.go
test/cursor_test.go

fixes #20  
The problem was that a query that returning anything other than a document, would cause Cursor.ReadDocument to fail because it returned with an error when the DocumentMeta could not be unmarshaled.
This PR ignores such errors, assuming that when the DocumentMeta cannot be unmarshaled, it is probably not there.

Fixed Cursor.ReadDocument for queries returning non-documents

---

http/connection.go
http/response_json.go
http/response_vpack.go

It turns out that `http.Transport` does not try to keep-alive connections unless you fully read the entire body AND close the body.
This PR ensures that is always the case.

Fix reading the response body to ensure keep-alive

---

collection_indexes.go
collection_indexes_impl.go
test/indexes_test.go

Fixes #48 
The added field is `NoDeduplicate` and not `Deduplicate` to avoid breaking changes.
Since the default value for `deduplicate` is `true`, and the go field will default to `false` if left unspecified, you would get unexpected `deduplicate=false` behavior when just updating the go driver without updating your code.
See also https://github.com/arangodb/arangodb/pull/2644

Added NoDeduplicate field for hash & skiplist index options

---

context.go
user.go
user_impl.go

This enable making the distinction between effective & configured database/collection access.
Note. This PR extends #62

Adding `WithConfigured`

---

connection.go
http/response_json.go
http/response_json_element.go
http/response_vpack.go
http/response_vpack_element.go
test/client_test.go
vst/response.go
vst/response_element.go

This PR adds a `Header(string)` function to the `Response` interface.
It is used to get response header values.

Adding Response.Header(string) & tests

---

context.go
edge_collection_documents_impl.go
test/edge_remove_test.go
test/edges_remove_test.go
test/vertex_remove_test.go
test/vertices_remove_test.go
vertex_collection_documents_impl.go

ReturnOld in combination with removing edges/vertices is not supported and now returns an `InvalidArgumentError`.
This PR depends on https://github.com/arangodb/arangodb/pull/4479

Fix ReturnOld/New for edge/vertex operations.

---

http/connection.go

Info came from https://groups.google.com/forum/#!topic/golang-nuts/WjFjmtqg3kA

Documented behavior for custom http.Transport wrt MaxIdleConnsPerHost field

---

agency/lock.go
agency/lock_errors.go
client_server_info.go
client_server_info_impl.go
test/agency_lock_test.go
test/cluster.sh
test/server_info_test.go

Added ServerID function

---

test/concurrency_test.go
test/util.go
vst/protocol/connection.go
vst/protocol/message_store.go
vst/protocol/transport.go

Due to the nature of the VST protocol, multiple concurrent messages
can already be "in-flight" at the same time on the same connection.
On high concurrency, it may be helpful to use multiple connections to 
the same server. This PR makes that possible.
The upper limit of the number of connections is controlled
by the new `ConnLimit` field in `TransportConfig`.

Added support for multiple VST connections per server

---

http/connection.go
test/concurrency_test.go

The HTTP client in the standard go-lang library (used by the go-drivers HTTP connection)
automatically adds new connections to a server when needed.
Under a highly-concurrent load, this can lead to more connections than the server
can safely handle.
This PR introduced a `ConnLimit` setting (with a default of 32) controlling the 
amount of concurrent requests made to a single server.

Added upper limit to the number of concurrent requests to a single server.

---

vst/protocol/connection.go
vst/protocol/transport.go

There was the potential for a connection being used by another go-routine before the configuration callback (typically with authentication) had finished.

Prevent a VST connection from being used before its configuration callback has finished

---

vst/protocol/chunk.go
vst/protocol/connection.go

This PR break the read chunk loop of a VST connection when it encounters to many errors in succession.
It also adds a few safety checks.

Prevent possible endless read chunk look in in VST connection

---

cluster_impl.go
context.go

This PR adds support for obtaining the job ID returned from a `CleanoutServer` request.
To get the JobID, prepare a context with `WithJobIDResponse`, passing in a reference to a string variable. After a successful call to `CleanoutServer`, the string variable will contain the job ID.

Added support for fetching job ID in CleanoutServer

---

client_impl.go

Added a separate function to access the endpoint via a database instead of _system.

SynchronizeEndpoints Database Route

---

cluster.go
test/cluster_test.go

Added Version and Engine to cluster health record.
This works does not work for 3.3.19 or rc 5.

Version/Engine Cluster Health

---

view_arangosearch.go
view_arangosearch_impl.go

According to the new specification some json fields changes and became optional.
In order to prevent the go driver from inserting `0` values at places that have a non-zero default value, I changes the types to pointer types. Hence they will be set to `nil` if not set.
API may changes again due to inconsistent naming of fields.

ArangoView API Changes

---

.gitignore
Makefile
cluster_impl.go
test/agency_test.go
test/cluster.sh
test/cluster_test.go
test/job_utils_test.go

Allow waiting for a job to finish.
For that, we need to open a connection to the agency with proper auth and protocol

Add job waiters in move shards tests

---

collection.go
test/collection_test.go

The field `globallyUniqueId` is required by the Arangosync to improve reading rom the Write ahead log

Add new field 'globallyUniqueId' to the collection info

---

replication_impl.go

This error is compared by the client from arangosync

Export batch error to be used by the client

---

client_impl.go
collection.go

I need one additional field in the CollectionProperties. This is added.
Furthermore, I noticed that ArangoDB > 3.6 returns a different error code on `/_api/cluster/endpoints` in case of a single server. This is tolerated now and fixes some tests.

Fix tests, add one field in CollectionProperties.

---

agency/agency.go
agency/agency_impl.go
agency/condition.go
agency/operation.go
agency/transaction.go
test/agency_test.go

**Warning**
Unfortunately, the transient endpoint is not handled by this PR because this endpoint returns response like `[true]` (it is []interface{}) and it can not be parsed by functions like `ParseBody` (it is map[string]interface{}) or `ParseArrayBody` (it is []map[string]interface{}.
We should have only one function which can parse a response exactly the same pattern is used in `func Unmarshal(data []byte, v interface{}) error` but this is out of my scope of my PR
**Commits before rebase:**
Write many transaction to the agency
Finish implementation for operation and conditions
Add integration tests for writing Transactions
Add integration tests using agency conditions
Remove transient key
Change functions' name
Avoid sending many transactions in one request

Change many entries in agency within one transaction

---

CHANGELOG.md
v2/connection/call.go

the `url.PathEscape` is used twice.
When the path in the URL is created `func NewUrl(parts ...string)` .
And when the request is created `func (j *httpRequest) URL() string` .

[BUGFIX] [V2] don't escape the path twice

---

query.go
test/cursor_test.go
test/query_test.go
v2/arangodb/database_query.go
v2/arangodb/meta.go
v2/tests/database_collection_operations_test.go

Added support for query option `shardIds` [APM-292]
[APM-292]: https://arangodb.atlassian.net/browse/APM-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

added support for shardIds query option for APM-292

---

cluster.go
cluster_impl.go
database_collections.go
database_collections_impl.go
v2/arangodb/database_collection_opts.go

Add new fields to the public structure `CreateCollectionOptions` (v1 and v2):
```
InternalValidatorType int    `json:"internalValidatorType,omitempty"`
IsDisjoint            bool  
SyncByRevision bool         `json:"syncByRevision,omitempty"`
```
Add new fields to the structure public `InventoryCollectionParameters` (only v1):
```
CacheEnabled bool `json:"cacheEnabled,omitempty"`
GloballyUniqueId string `json:"globallyUniqueId,omitempty"`
InternalValidatorType int `json:"internalValidatorType,omitempty"`
IsDisjoint bool `json:"isDisjoint,omitempty"`
IsSmartChild bool `json:"isSmartChild,omitempty"`
Schema            *CollectionSchemaOptions `json:"schema,omitempty"`
ShadowCollections []int
```
Fields in structures were sorted alphabetically, so that is why we can see many changes.
New …

[Feature] Tg 224/disjoint smart graphs

---

MAINTAINERS.md
test/cluster.sh

Two problems fixed in this PR:
1) on MacOS systems the `STARTERARGS` env variable was always rewritten with static value
2) when using cgroups v2, arangodb-starter fails to automatically discover the container name. Providing `--docker.container` option disable auto discovery. Failing code in starter: https://github.com/arangodb-helper/arangodb/blob/60de446c4634218d81054bc754af6b2fb2f27413/docker.go#L58

Fix running test cluster under cgroups v2

---

CHANGELOG.md
database_impl.go
database_transactions.go
test/database_transaction_test.go
transaction.go

Add support for exclusive field for transaction options

---

CHANGELOG.md
cursor_impl.go
test/cursor_test.go

Fixes rounding error.
The value returned by arangod is in seconds: https://github.com/arangodb/arangodb/blob/devel/js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js#L2078
Closes #373

Fix cursor executionTime statistics getter

---

CHANGELOG.md
collection_indexes_impl.go
test/indexes_test.go

Fix for https://github.com/arangodb/go-driver/issues/393

Fix selectivityEstimate Index field type

---

CHANGELOG.md
cluster.go
cluster_impl.go
collection.go

Set `lastValue` proper field type

---

.travis.yml
test/view_test.go

This test shows example usage of pipeline analyzer with view

Add analyzer test

---

CHANGELOG.md
cluster.go
cluster_impl.go

example output from `/clusterInventory` API endpoint:
```
"computedValues": [
{
"name": "date-timestamp-value",
"expression": "RETURN DATE_NOW()",
"computeOn": [
"insert"
],
"overwrite": false,
"failOnWarning": true,
"keepNull": true
}
],
```

Add support for `computedValues` into collection inventory

---

test/view_test.go

This reverts commit 756f3a4d4496b3d5c04b6777a9552ae5893ac1a0.

Revert "GT-167 Temporary disable failing AQL tests for 3.10 (#419)"

---

CHANGELOG.md
client_impl.go
cluster/cluster.go
connection.go
http/authentication.go
http/connection.go
test/client_test.go

It is not possible to use same connection when calling `NewClient` with different `Authentication` parameter concurrently.
Use-case:
1) create one Connection
2) Use this connection to create new driver.Client but for different users (provided in Config.Authentication). Use this connection concurrently.
3) It will not work occasionally because NewClient calls "SetAuhtentication" on Connection object
This will never work for VST connections - it is not designed for use-case.

GT-292 Fix reusing same connection with different Authentication parameters

---

CHANGELOG.md
test/arangosearch_analyzers_test.go
test/client_test.go
test/view_test.go
view_arangosearch.go

https://www.arangodb.com/docs/3.9/arangosearch-views.html#link-properties
https://www.arangodb.com/docs/3.9/arangosearch-views.html#view-properties
PrimaryKeyCache:
https://github.com/arangodb/docs/pull/1191
For now GET /properties does not work properly in 3.9-nightly image - one sub test will fail until fix.

Add cache for ArangoSearchView Link and StoredValue types and `primarySortCache` for ArangoSearchView type

---

CHANGELOG.md
error.go

https://www.arangodb.com/docs/stable/appendix-error-codes.html#external-arangodb-storage-errors

Add IsExternalStorageError to check for external storage errors.

---

README.md

it wasn't working properly on some sites because of incorrect headers/redirects at main ArangoDB site.
e.g. ![at pkg.go.dev](https://i.imgur.com/TZgdbJt.png)

Fix ArangoDB logo image in Readme

---

CHANGELOG.md
collection_indexes_impl.go
test/index_ensure_test.go

Fix for https://github.com/arangodb/go-driver/issues/291

GT-336 TTL index creation fails when expireAt is 0 - fix

---

CHANGELOG.md
client_databases.go
database.go
test/database_test.go
v2/arangodb/client_database.go
v2/arangodb/database_opts.go
v2/tests/database_transactions_test.go

For many client tools, for example `feed`, we need the go-driver to create a replication version 2 database.

Add replication version option for database creation.

---

CHANGELOG.md
cluster_impl.go
replication_impl.go
revision.go

In all places where we use DB name in URL path, it is escaped using pathEscape function but in few places it is missing for some reason. That potentially could lead to the problem when using DB name with non-ANSI characters.

Fix potential bug with DB name escaping for URL when requesting replication-related API

---

CHANGELOG.md
query.go
test/cursor_test.go
test/doc.go
v2/arangodb/cursor.go
v2/arangodb/cursor_impl.go
v2/arangodb/database_query.go
v2/arangodb/utils.go
v2/tests/database_collection_operations_test.go

- Fix optimizers rules options
- Users can set optimizers rules
- Add support for plan cursor in v2

Support optimizer rules in AQL queries

---

test/index_ensure_test.go

Optimization was removed from 3.11 version, so test must work since 3.12.

OptimizeTopK available since 3.12

---

test/view_test.go

Fix `OptimizeTopK` field for ArangoSearch. This field was removed from 3.11.
It requires only fix for go-driver v1.

Fix arangosearch optimizeTopK support

---

CHANGELOG.md
agency/agency_connection.go

When using Cluster mode, the client can see unexpected behavior when passing `WithRawResponse(ctx, value)` context:
agencyConnection sends requests in parallel goroutines. That results in race condition: the rawResponse might not match to the returned response.
e.g that can happen when one agent returns a normal response (200 with non-empty body) but other agent returns status 307 (redirect to leader with empty body). In result user will get body from first response but rawResponse value will be set to empty.
The PR changes behavior such that agency connection will not run requests in parallel when user specifies WithRawResponse/WithResponse options.

Fix race when using WithRawResponse/WithResponse context with agencyConnection

---

CHANGELOG.md
edge_collection_documents_impl.go
test/edge_remove_test.go
test/edges_remove_test.go
test/vertex_remove_test.go
test/vertices_remove_test.go
vertex_collection_documents_impl.go

It's reverting https://github.com/arangodb/go-driver/pull/92/files since Return old in edge/vertex operations is working fine since 3.8

[V1] Revert ReturnOld for edge/vertex operations

---

CHANGELOG.md
client.go
client_impl.go
client_test.go

There is no clean way to fix that implementation without introducing NewClient2 function which might be very confusing.

Deprecate ClientConfig.SynchronizeEndpointsInterval due to bug in implementation

---

v2/tests/database_collection_doc_create_test.go
v2/tests/database_collection_doc_delete_test.go
v2/tests/database_collection_doc_replace_test.go
v2/tests/database_collection_doc_update_test.go

Silent removal has been fixed for cluster mode in 3.12

GT-376 Restore tests for silent doc removal

---

v2/README.md

Official package index (https://pkg.go.dev/github.com/arangodb/go-driver ) now prompts that go-driver has a newer 'v2' version. We should warn the users that it is not production-ready yet.

[V2] Update README.md

---

Makefile

Currently it is DDoSing the arangod in single and active failover mode such that arangod can't handle the creation of  all DBs/Collections (it tries to update user permissions but fails after 10 attempts). This happens on nodes with high number of cores, e.g. 36 because default value of parallelism is GOMAXPROCS(=Num of cores)
It does not happen with v1 tests because we don't try to execute so many tests in parallel there.

Make v2 tests less aggressive

---

test/database_transaction_test.go
v2/tests/database_transactionsjs_test.go

Check for substring instead of exact match to ensure more V8 versions are supported

Improve tests for JS transactions

---

README.md

Updated the "Getting started" link as it was redirecting to the https://arangodb.com/ page

Updated README.md link

---

README.md
v2/README.md

Follow-up PR for
- #628 
To be merged once this PR has been merged and the docs published!

OAS-10132 | Docs: Link to external v2 tutorial

---

v2/CHANGELOG.md
v2/arangodb/collection_documents_create.go
v2/arangodb/collection_documents_delete.go
v2/arangodb/collection_documents_replace.go
v2/arangodb/collection_documents_update.go
v2/arangodb/database_query.go

OAS-10230 Adjust Cursor options

---

Makefile
test/cluster.sh
test/jwt.sh
test/on_failure.sh

Changes:
* Added agency dump when `DUMP_AGENCY_ON_FAILURE=<file_path>` to be saved in the fiile path
eg. `DUMP_AGENCY_ON_FAILURE=agency_dump.json make run-tests-cluster-vpack-no-auth` 
*  Made arangodb_starter start test containers in host network; `--net=host` instead of running an alpine container to serve that funciton
* Separated all functions that need to be executed when go-driver-test docker container returns any messages (fails) to a separete file `on_failure.sh`
Requirements
* needs `jq` installed on host in order to parse the JSON responses that are received from the database API when creating agency dumps.

OAS-10368 Grab Agenecy dump on test failures in go-driver

---

v2/arangodb/collection_documents_replace.go
v2/arangodb/collection_documents_replace_impl.go
v2/arangodb/collection_documents_update.go
v2/arangodb/collection_documents_update_impl.go
v2/arangodb/meta.go
v2/tests/database_collection_doc_replace_test.go
v2/tests/database_collection_doc_update_test.go

Extended DocumentMeta with DocumentMetaWithOldRev to support the OldRev field response from Replace and Update operations.

[Feature] OAS-10519 Expose OldRev Document Metadata In go-driver v2

---

v2/arangodb/collection_documents_replace_impl.go

A fix has been added https://github.com/arangodb/go-driver/issues/644 https://github.com/arangodb/go-driver/pull/645

[Fix] OAS 10652 Replace documents does an update PATCH instead of a replace PUT

---

v2/arangodb/cursor.go
v2/arangodb/cursor_impl.go
v2/connection/connection.go
v2/tests/cursor_test.go

https://github.com/arangodb/go-driver/issues/542

[Feature] Get Raw JSON bytes from query Cursor

---

.circleci/config.yml
v2/CHANGELOG.md
v2/arangodb/client_foxx.go
v2/arangodb/client_foxx_impl.go
v2/tests/foxx_test.go

This includes the following Foxx - related endpoints:
1.	GET - /_db/{database-name}/_api/foxx
2.	GET - /_db/{database-name}/_api/foxx/service
3.	DELETE - /_db/{database-name}/_api/foxx/service
4.	PUT - /_db/{database-name}/_api/foxx/service
5.	PATCH -	/_db/{database-name}/_api/foxx/service
6.	GET - /_db/{database-name}/_api/foxx/configuration
7.	PATCH -	/_db/{database-name}/_api/foxx/configuration
8.	PUT - /_db/{database-name}/_api/foxx/configuration
9.	GET - /_db/{database-name}/_api/foxx/dependencies
10.	PATCH -	/_db/{database-name}/_api/foxx/dependencies
11.	PUT - /_db/{database-name}/_api/foxx/dependencies
12.	GET - /_db/{database-name}/_api/foxx/scripts
13.	POST - /_db/{database-name}/_api/foxx/scripts/{name}
14.	POST - /_db/{database-name}/_api/foxx/tests
15.	POST - …

Add V2 endpoints for Foxx Service
