collection.go
collection_impl.go
connection.go
context.go
error.go
examples/create_documents.go
http/mergeObject.go
http/request.go
http/response.go
http/response_element.go
meta.go
test/document_create_test.go
test/documents_create_test.go
test/documents_remove_test.go
test/documents_replace_test.go
test/documents_update_test.go

Adding multi document requests

---

Makefile
collection.go
collection_impl.go
edge_collection_impl.go
http/connection.go
test/client_test.go
test/cluster.sh
test/collection_test.go
test/edge_collection_test.go
test/edge_create_test.go
test/edge_remove_test.go
test/edge_replace_test.go
test/edge_update_test.go
test/edges_create_test.go
test/edges_import_test.go
test/edges_remove_test.go
test/edges_replace_test.go
test/edges_update_test.go
vertex_collection_impl.go

Running the unit tests against an ArangoDB cluster.

Cluster tests

---

.travis.yml
Makefile
connection.go
content_type.go
http/connection.go
http/content_type.go
http/request_json.go
http/request_json_test.go
http/request_vpack.go
http/response_json.go
http/response_json_element.go
http/response_vpack.go
http/response_vpack_element.go
test/client_test.go
test/document_update_test.go
test/documents_import_test.go
test/documents_update_test.go
test/edge_update_test.go
test/edges_import_test.go
test/edges_update_test.go
test/util.go
test/vertex_update_test.go
test/vertices_import_test.go
test/vertices_update_test.go

Adding support for HTTP+Velocypack transport.

Supporting Velocypack content-type (instead of JSON) (wip)

---

Makefile
test/cluster.sh
test/database_test.go

This PR updates the tests to use `arangodb` (starter) 0.7.

Starter update

---

database.go
database_impl.go
test/collection_test.go

Added a `Database.EngineInfo` function, used to fetch information about the storage engine being used by the database.

Adding Storage engine detection

---

http/connection.go
test/user_auth_test.go

Convert 401 text/plain response to proper ArangoError

---

collection.go
collection_impl.go
edge_collection_impl.go
http/connection.go
test/user_auth_test.go
test/util.go
user.go
user_impl.go
vertex_collection_impl.go

Adding additional requests for setting/getting/removing database & collection access rules.

Supporting additional user access functions

---

authentication.go
client.go
client_impl.go
connection.go
http/authentication.go
http/connection.go
http/request_json.go
http/request_vpack.go
vst/request.go

Added support for passing a raw authentication header.

Raw authentication

---

context.go
database_collections_impl.go

This code requires a yet to be released `arangod` version

Added WithEnforceReplicationFactor

---

database_collections.go

Added DistributeShardsLike field to CreateCollectionOptions

---

client.go
client_server_admin.go
client_server_admin_impl.go
context.go
database_collections.go
test/server_mode_auth_test.go
test/server_mode_test.go
user.go
user_impl.go

Note: This PR extends #64 
TODO:

Server mode (get/set)

---

Makefile
cluster/cluster.go
error.go
test/client_test.go
test/cluster.sh

This PR adds support for the go-driver to connection to ArangoDB servers running in resilient single server mode.

Resilientsingle support

---

Makefile

Fixing SWTSECRET -> JWTSECRET

---

test/collection_test.go

After a load/unload the status can be unloading/loading. Give some time for that

Allow for some time to reach intended status

---

client.go
client_cluster_impl.go
client_impl.go
client_replication.go
client_replication_impl.go
client_server_info.go
client_server_info_impl.go
cluster.go
cluster/cluster.go
context.go
replication.go
replication_impl.go
test/replication_test.go

Provides server specific `DatabaseInventory`.
This PR extends #89

Replication interface added.

---

database.go
database_impl.go
test/database_test.go

Database.Info() added

---

context.go
replication.go
replication_impl.go
test/client_test.go
test/cluster_test.go
test/replication_test.go
test/user_auth_test.go

This branch will correspond to this pull request: https://github.com/arangodb/arangodb/pull/4715

Active-Failover with Velocystream

---

cursor.go
cursor_impl.go
query.go
test/cursor_test.go
test/util.go

#99 should be merged first, then travis will also run green again

Add support for stream query cursor

---

collection_document_impl.go
context.go
edge_collection_documents_impl.go
test/document_create_test.go
test/document_remove_test.go
test/document_replace_test.go
test/document_update_test.go
test/documents_create_test.go
test/documents_import_test.go
test/documents_remove_test.go
test/documents_replace_test.go
test/documents_update_test.go
vertex_collection_documents_impl.go

Fixed expected status code for operations on collections that have waitForSync enabled

---

vst/protocol/transport.go

The test showed that an authenticated VST test run fails on the very first connection only.
This very first test creates a connection where the authentication callback fails.
When that fails, the connection was still left "usable", which caused the failures.

Close the connection when the initial onCreatedCallback fails

---

vst/protocol/connection.go
vst/protocol/message.go
vst/protocol/message_store.go

This PR adds extra concurrency safety to prevent writing to a closed channel.
It should fix #86.

Adding extra concurrency-safety for VST

---

cluster/doc.go
http/doc.go
test/doc.go
util/doc.go
vst/doc.go
vst/protocol/doc.go

This PR extends the docs are they are shown on godoc.org.

Added package level docs

---

agency/agency_connection.go

This PR fixes the AgencyConnection wrt results from followers.

Fixed AgencyConnection in the context of authentication

---

cursor_impl.go
test/cursor_test.go

Fixing Query(return nul) resulting in panic

---

collection_document_impl.go
collection_documents.go
edge_collection_documents_impl.go
test/documents_create_test.go
test/edges_create_test.go
test/vertices_create_test.go
vertex_collection_documents_impl.go

Added a multi-document read operation.

Added Collection.ReadDocuments

---

database_collections.go
database_graphs.go
query.go

See https://github.com/arangodb/arangosync/pull/432#issuecomment-406014670

Docs: Always call it Enterprise Edition

---

collection_indexes_impl.go
index.go
index_impl.go
test/index_ensure_test.go
test/indexes_test.go

Added `Type()` to `Index`.

---

CHANGELOG.md
cluster.go
collection_indexes_impl.go
database.go
database_views.go
database_views_impl.go
test/cluster_test.go
test/indexes_test.go
test/view_test.go
view.go
view_arangosearch.go
view_arangosearch_impl.go
view_impl.go

fixes https://github.com/arangodb/team-clifton-planning/issues/13
fixes https://github.com/arangodb/team-clifton-planning/issues/35

Adding Views API

---

collection_document_impl.go
context.go
cursor_impl.go
database_impl.go
edge_collection_documents_impl.go
test/document_read_test.go
test/view_test.go
vertex_collection_documents_impl.go

Fixes arangodb/team-clifton-planning#47.
[Docs](https://github.com/arangodb/documents/blob/master/Driver/DirtyReads.md)

Dirty Reads

---

go.mod
go.sum

Adding go (1.11) module support

---

example_graph_test.go

Lars Maier has translated the Java graph examples in our manual to golang.

Added graph example.

---

error.go
test/client_test.go
test/user_auth_test.go

Retry on authentication tests. Permissions propagate slowly. Retry to obtain endpoints.

Test Fix Auth + Sync Endpoints

---

cluster.go

Added SyncStatus to Health record. And more.

Updated Health Record structure.

---

index.go
index_impl.go
test/indexes_test.go

added edge index

---

test/cursor_test.go

Added test for WithQueryFullCount context attribute.

WithQueryFullCount test

---

.travis.yml
Makefile
cluster.go
cluster_impl.go
collection.go
collection_impl.go
database_collections.go
database_collections_impl.go
test/cluster_test.go
test/collection_test.go

Added SmartJoinAttribute support to go-driver.

SmartJoins

---

cluster.go
cluster_impl.go
collection.go
collection_impl.go
database_collections.go
database_collections_impl.go
test/cluster_test.go
test/collection_test.go

Sharding Strategy

---

Makefile

Otherwise, Jenkins matrix jobs with limit to "test" Linux nodes doesn't work

Fix ability to run on Jenkins in path/a&&b

---

http/response_json.go

Do not recurse into non struct types.
Fixes https://github.com/arangodb/go-driver/issues/40

Unmarshaling error

---

Makefile

http://jenkins.arangodb.biz:8080/job/arangodb-ANY-go-driver-matrix/192/

Bug fix/cleanup without error

---

client_admin_backup.go
client_admin_backup_impl.go
example_graph_test.go
test/backup_test.go

Also: Fix instability in hotbackup tests.

Rename forceBackup to allowInconsistent.

---

.travis.yml
test/cursor_test.go

Change memory limit for cursor tests

Change cursor memory limit in test

---

test/collection_test.go
test/database_test.go

http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-go-driver-matrix/468/

Skip Unload on RocksDB

---

.gitignore
client_databases.go
cluster.go
cluster_impl.go
collection.go
collection_impl.go
context.go
database.go
database_collections.go
database_collections_impl.go
go.mod
go.sum
query.go
test/arangosearch_analyzers_test.go
test/client_test.go
test/collection_test.go
test/cursor_test.go
test/database_collection_defaults_test.go
test/database_test.go
test/server_statistics_test.go
view_arangosearch.go

Implementation of ArangoD 3.6 API

ArangoD 3.6 Changes

---

.travis.yml
Makefile
test/foxx_test.go

Foxx service is downloaded only once to the pipeline worker machine for better performance and it is more resilient

Get foxx service only once per pipeline worker machine

---

Makefile
test/cluster.sh

Minor addition to have API check job in PRs: http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-go/
oskar companion PR: https://github.com/arangodb/oskar/pull/235

Minor changes to run API check in Jenkins PRs

---

http/authentication.go
http/authentication_test.go
http/connection.go
test/client_test.go

it is required by the arangosync to reload connection in case of unauthorized status

Repeat requests connection

---

CHANGELOG.md
collection.go
collection_impl.go
test/collection_test.go
v2/arangodb/client_database.go
v2/arangodb/collection_opts.go
v2/arangodb/database_collection_opts.go
v2/arangodb/database_opts.go
v2/tests/database_collection_operations_test.go

- It fixes fetching collection shards info from the ArangoD in v1.
- It introduces using satellite collections in v2.

[ Bugfix ] Satelite replication factor for shards information

---

test/document_update_test.go

Ensures that `WithMergeObjects` context option works as expected.
Closes issue #365

Add test for document update with mergeObjects option

---

edge_collection_documents_impl.go

Just a type fix that make a sentence hard to understand.
\cc @jwierzbo

Fix misspell

---

CHANGELOG.md
collection_indexes.go
collection_indexes_impl.go

GT-138 Add missing `deduplicate` param to PersistentIndex

---

test/arangosearch_analyzers_test.go

I've added this test for the time when the feature will be implemented (uploading ML models via API), but it's still not even for the arangodb:devel.

Remove tests which are not working due to absence of required API in arangod

---

.travis.yml

- add resilientsingle
- remove 3.8.x branches from testing
- use 3.10 instead of 3.10-preview

Update Travis test matrix

---

CHANGELOG.md
v2/connection/connection.go
v2/connection/connection_http_response.go
v2/connection/connection_http_response_test.go

v1 has this function and having this in v2 will simplify migration

v2: add Response.CheckStatus

---

CHANGELOG.md
test/arangosearch_analyzers_test.go
view_arangosearch.go

Add geo_s2 analyzer type and `format` analyzer's property

support for geo_s2 analyzers

---

.golangci.yaml
.travis.yml
CHANGELOG.md
Makefile
vst/protocol/chunk_test.go

- golangci-lint version updated
- enable test for VST: chunk_test.go fixed

Use Go 1.20.3 for testing. Add govulncheck to pipeline

---

CHANGELOG.md
context.go
v2/arangodb/collection_documents_create.go
v2/arangodb/collection_documents_delete.go
v2/arangodb/collection_documents_update.go

Unfortunately, it is not possible to create tests for this change.

Add support for refilling index caches

---

.travis.yml
Makefile
test/backup_test.go
test/client_test.go
test/server_logs_test.go
v2/tests/admin_log_test.go
v2/tests/run_wrap_test.go

When environment is available, it does not mean that healthiness can be fetched right away. Sometimes we must wait for it.

Wait for health

---

CHANGELOG.md
v2/connection/call.go
v2/connection/connection.go
v2/connection/connection_http_internal.go
v2/connection/connection_pool.go
v2/connection/connection_with_reauthentication.go
v2/connection/retry_wrapper.go
v2/tests/call_test.go

- consistent return of Response

[V2] Add optional status code checks

---

CHANGELOG.md
context.go
context_read.go
test/database_transaction_test.go
test/document_create_test.go
test/documents_update_test.go

Fix for https://github.com/arangodb/go-driver/issues/485

GT-461 Expose getters for Context values

---

CHANGELOG.md
collection.go
collection_impl.go
edge_collection_impl.go
test/edge_collection_test.go
test/vertex_collection_test.go
vertex_collection_impl.go

This PR contains the same code as Wolfx's but his fork repo has been deleted.
Please consider to review this feature as it's still relevant and very useful.
I can make the same changes for the v2 driver if required.

Add Rename collection

---

CHANGELOG.md
client_databases_impl.go
context.go
database_collections_impl.go
test/collection_test.go
test/database_test.go
v2/CHANGELOG.md
v2/arangodb/client_database.go
v2/arangodb/client_database_impl.go
v2/arangodb/database_collection.go
v2/arangodb/database_collection_impl.go
v2/tests/database_collection_operations_test.go
v2/tests/database_test.go
v2/tests/database_transactions_test.go
v2/tests/helper_test.go

Fixes: https://github.com/arangodb/go-driver/issues/570

GT-570 Allow skipping validation for Database and Collection existence
